///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Epiroc
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Calcuator recording.
    /// </summary>
    [TestModule("c9848a99-3124-4444-b96f-6f692d627426", ModuleType.Recording, 1)]
    public partial class Calcuator : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SalesforceRepository repository.
        /// </summary>
        public static SalesforceRepository repo = SalesforceRepository.Instance;

        static Calcuator instance = new Calcuator();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Calcuator()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Calcuator Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Num7Button' at 46;24.", repo.Calculator.Num7ButtonInfo, new RecordItemIndex(0));
            repo.Calculator.Num7Button.Click("46;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.SomeText' at 10;4.", repo.Calculator.SomeTextInfo, new RecordItemIndex(1));
            repo.Calculator.SomeText.Click("10;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.Text9' at 5;12.", repo.Calculator.Text9Info, new RecordItemIndex(2));
            repo.Calculator.Text9.Click("5;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.SomeText1' at 5;7.", repo.Calculator.SomeText1Info, new RecordItemIndex(3));
            repo.Calculator.SomeText1.Click("5;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Calculator.SomeText2' at 5;9.", repo.Calculator.SomeText2Info, new RecordItemIndex(4));
            repo.Calculator.SomeText2.Click("5;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'Calculator.NormalOutput'.", repo.Calculator.NormalOutputInfo, new RecordItemIndex(5));
            Validate.NotExists(repo.Calculator.NormalOutputInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
