///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Epiroc
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CodeModules recording.
    /// </summary>
    [TestModule("d0766fb1-5392-42b1-aeb1-a1f7dc06e6fd", ModuleType.Recording, 1)]
    public partial class CodeModules : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EpirocRepository repository.
        /// </summary>
        public static EpirocRepository repo = EpirocRepository.Instance;

        static CodeModules instance = new CodeModules();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CodeModules()
        {
            FirstName = "Mubin";
            LastName = "Kadiwala";
            Age = "35";
            Category = "Testing";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CodeModules Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("efc02edc-1d3c-4cf4-9229-752f6d2cd92b")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("23359fd0-e635-4d69-964f-e3a876f79a54")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Category.
        /// </summary>
        [TestVariable("808814a3-e7ec-4eb8-8bfd-834506eda953")]
        public string Category
        {
            get { return repo.Category; }
            set { repo.Category = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("b48bc0de-3127-4c6e-8677-6fe4241727e9")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Age.
        /// </summary>
        [TestVariable("a6032833-9942-409a-bf45-e025354b8ab7")]
        public string Age
        {
            get { return repo.Age; }
            set { repo.Age = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            MergedUserCodeMethod(repo.DemoApp.Login.FirstNameInfo, repo.DemoApp.Login.LastNameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TabStandard.Open' at Center.", repo.TabStandard.OpenInfo, new RecordItemIndex(1));
            repo.TabStandard.Open.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Testing' at 99;9.", repo.List1000.TestingInfo, new RecordItemIndex(2));
            repo.List1000.Testing.Click("99;9");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'TabStandard.Age' at 36;6.", repo.TabStandard.AgeInfo, new RecordItemIndex(3));
            //repo.TabStandard.Age.DoubleClick("36;6");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'TabStandard.Age'.", repo.TabStandard.AgeInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.TabStandard.Age);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Age' with focus on 'TabStandard.Age'.", repo.TabStandard.AgeInfo, new RecordItemIndex(5));
            repo.TabStandard.Age.PressKeys(Age);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TabStandard.RdbMale' at Center.", repo.TabStandard.RdbMaleInfo, new RecordItemIndex(6));
            repo.TabStandard.RdbMale.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.BtnAddPerson' at 44;6.", repo.DemoApp.BtnAddPersonInfo, new RecordItemIndex(7));
            repo.DemoApp.BtnAddPerson.Click("44;6");
            Delay.Milliseconds(0);
            
            //CheckSQL(Category);
            //Delay.Milliseconds(0);
            
            //TypeText(repo.DemoApp.Login.FirstName, "Hello");
            //Delay.Milliseconds(0);
            
            //TypeText(repo.DemoApp.Login.LastName, "World");
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
