///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Epiroc
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the EpirocRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6f2b0937-858c-4aa0-96dd-4c7a89b06b62")]
    public partial class EpirocRepository : RepoGenBaseFolder
    {
        static EpirocRepository instance = new EpirocRepository();
        EpirocRepositoryFolders.DemoAppAppFolder _demoapp;
        EpirocRepositoryFolders.TabStandardFolder _tabstandard;
        EpirocRepositoryFolders.List1000AppFolder _list1000;
        EpirocRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;
        EpirocRepositoryFolders.HowToCreateAUserRatingScorecardAppFolder _howtocreateauserratingscorecard;
        EpirocRepositoryFolders.ExplorerAppFolder _explorer;
        EpirocRepositoryFolders.Form1AppFolder _form1;
        EpirocRepositoryFolders.Paint3DAppFolder _paint3d;
        EpirocRepositoryFolders.RanorexAppFolder _ranorex;

        /// <summary>
        /// Gets the singleton class instance representing the EpirocRepository element repository.
        /// </summary>
        [RepositoryFolder("6f2b0937-858c-4aa0-96dd-4c7a89b06b62")]
        public static EpirocRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public EpirocRepository() 
            : base("EpirocRepository", "/", null, 0, false, "6f2b0937-858c-4aa0-96dd-4c7a89b06b62", ".\\RepositoryImages\\EpirocRepository6f2b0937.rximgres")
        {
            _demoapp = new EpirocRepositoryFolders.DemoAppAppFolder(this);
            _tabstandard = new EpirocRepositoryFolders.TabStandardFolder(this);
            _list1000 = new EpirocRepositoryFolders.List1000AppFolder(this);
            _ranorexvipdatabasetestwebapplicatio = new EpirocRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
            _howtocreateauserratingscorecard = new EpirocRepositoryFolders.HowToCreateAUserRatingScorecardAppFolder(this);
            _explorer = new EpirocRepositoryFolders.ExplorerAppFolder(this);
            _form1 = new EpirocRepositoryFolders.Form1AppFolder(this);
            _paint3d = new EpirocRepositoryFolders.Paint3DAppFolder(this);
            _ranorex = new EpirocRepositoryFolders.RanorexAppFolder(this);
        }

#region Variables

        string _Age = "35";

        /// <summary>
        /// Gets or sets the value of variable Age.
        /// </summary>
        [TestVariable("dac051ce-bf4e-407f-b2af-c316fdf3e621")]
        public string Age
        {
            get { return _Age; }
            set { _Age = value; }
        }

        string _Gender = "Male";

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("b48bc0de-3127-4c6e-8677-6fe4241727e9")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

        string _Catogory = "";

        /// <summary>
        /// Gets or sets the value of variable Catogory.
        /// </summary>
        [TestVariable("f534c418-aa00-4853-ba3b-49e1c8e8c2f8")]
        public string Catogory
        {
            get { return _Catogory; }
            set { _Catogory = value; }
        }

        string _Category = "Testing";

        /// <summary>
        /// Gets or sets the value of variable Category.
        /// </summary>
        [TestVariable("808814a3-e7ec-4eb8-8bfd-834506eda953")]
        public string Category
        {
            get { return _Category; }
            set { _Category = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6f2b0937-858c-4aa0-96dd-4c7a89b06b62")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DemoApp folder.
        /// </summary>
        [RepositoryFolder("b8a7bc6c-04fb-4ca6-93d4-2c44f78c2c64")]
        public virtual EpirocRepositoryFolders.DemoAppAppFolder DemoApp
        {
            get { return _demoapp; }
        }

        /// <summary>
        /// The TabStandard folder.
        /// </summary>
        [RepositoryFolder("2361754b-4a5c-4260-89b4-89f5afb417f9")]
        public virtual EpirocRepositoryFolders.TabStandardFolder TabStandard
        {
            get { return _tabstandard; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("a21e7b00-0963-46b3-b1ae-677b87a0ab01")]
        public virtual EpirocRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("55446e64-e028-4fb0-a16c-52710daf9385")]
        public virtual EpirocRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }

        /// <summary>
        /// The HowToCreateAUserRatingScorecard folder.
        /// </summary>
        [RepositoryFolder("7011a435-979b-4fe1-8005-f106276d604b")]
        public virtual EpirocRepositoryFolders.HowToCreateAUserRatingScorecardAppFolder HowToCreateAUserRatingScorecard
        {
            get { return _howtocreateauserratingscorecard; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("dfecbb30-89a0-451e-beac-7b638b8a0c99")]
        public virtual EpirocRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("6ff410e8-7fb8-49be-b9d0-38ee8c7def27")]
        public virtual EpirocRepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }

        /// <summary>
        /// The Paint3D folder.
        /// </summary>
        [RepositoryFolder("7ee59637-ee41-4f3e-b335-d7c60cd2ef04")]
        public virtual EpirocRepositoryFolders.Paint3DAppFolder Paint3D
        {
            get { return _paint3d; }
        }

        /// <summary>
        /// The Ranorex folder.
        /// </summary>
        [RepositoryFolder("b935fa11-e3eb-4eee-becf-c5799edd1fbe")]
        public virtual EpirocRepositoryFolders.RanorexAppFolder Ranorex
        {
            get { return _ranorex; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class EpirocRepositoryFolders
    {
        /// <summary>
        /// The DemoAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("b8a7bc6c-04fb-4ca6-93d4-2c44f78c2c64")]
        public partial class DemoAppAppFolder : RepoGenBaseFolder
        {
            EpirocRepositoryFolders.RxTabcontrolFolder _rxtabcontrol;
            EpirocRepositoryFolders.LoginFolder _login;
            RepoItemInfo _rxbuttonexitInfo;
            RepoItemInfo _introductionInfo;
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _imagebasedautomationInfo;
            RepoItemInfo _chkshowimageInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new DemoApp  folder.
            /// </summary>
            public DemoAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoApp", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "b8a7bc6c-04fb-4ca6-93d4-2c44f78c2c64", "")
            {
                _rxtabcontrol = new EpirocRepositoryFolders.RxTabcontrolFolder(this);
                _login = new EpirocRepositoryFolders.LoginFolder(this);
                _rxbuttonexitInfo = new RepoItemInfo(this, "RxButtonExit", "button[@controlname='RxButtonExit']", "", 30000, null, "bbec160c-e0c2-48c5-afcc-be6e26792845");
                _introductionInfo = new RepoItemInfo(this, "Introduction", "?/?/tabpage[@accessiblename='Introduction']", "", 30000, null, "9f43e0e3-89bc-48e7-b6dd-9b39963b6ba1");
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/tabpage[@controlname='RxTabIntroduction']/?/?/text[@accessiblename='Enter your name']", "", 30000, null, "1492da08-69de-4364-be29-c4f264aab911");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", ".//button[@controlname='btnSubmitUserName']", "", 30000, null, "00c51a11-bb60-4097-9822-2fbfc2f14f4d");
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "f0e2b21a-1431-4464-94cd-bea197f3c643");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", ".//button[@controlname='btnAddPerson']", "", 30000, null, "0b8da5f6-5ff0-4615-8e55-7a124c80c4c4");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", ".//text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "36cb546b-427a-4f4a-a0b6-2f56eb5e2d4d");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", ".//button[@controlname='btnDeletePerson']", "", 30000, null, "cbf9c831-8d0d-4016-b364-837e17d8e71d");
                _imagebasedautomationInfo = new RepoItemInfo(this, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", "", 30000, null, "a1c43a20-073f-44cd-870a-3628914f712e");
                _chkshowimageInfo = new RepoItemInfo(this, "ChkShowImage", ".//checkbox[@controlname='chkShowImage']", "", 30000, null, "c73b7c3e-c39f-48d8-b1a3-ee18cc7feb17");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", ".//text[@controlname='lblWelcomeMessage']", "", 30000, null, "f5cb2886-f452-4640-a3a8-2d3c14f80937");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b8a7bc6c-04fb-4ca6-93d4-2c44f78c2c64")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b8a7bc6c-04fb-4ca6-93d4-2c44f78c2c64")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxButtonExit item.
            /// </summary>
            [RepositoryItem("bbec160c-e0c2-48c5-afcc-be6e26792845")]
            public virtual Ranorex.Button RxButtonExit
            {
                get
                {
                    return _rxbuttonexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RxButtonExit item info.
            /// </summary>
            [RepositoryItemInfo("bbec160c-e0c2-48c5-afcc-be6e26792845")]
            public virtual RepoItemInfo RxButtonExitInfo
            {
                get
                {
                    return _rxbuttonexitInfo;
                }
            }

            /// <summary>
            /// The Introduction item.
            /// </summary>
            [RepositoryItem("9f43e0e3-89bc-48e7-b6dd-9b39963b6ba1")]
            public virtual Ranorex.TabPage Introduction
            {
                get
                {
                    return _introductionInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Introduction item info.
            /// </summary>
            [RepositoryItemInfo("9f43e0e3-89bc-48e7-b6dd-9b39963b6ba1")]
            public virtual RepoItemInfo IntroductionInfo
            {
                get
                {
                    return _introductionInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("1492da08-69de-4364-be29-c4f264aab911")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("1492da08-69de-4364-be29-c4f264aab911")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("00c51a11-bb60-4097-9822-2fbfc2f14f4d")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("00c51a11-bb60-4097-9822-2fbfc2f14f4d")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("f0e2b21a-1431-4464-94cd-bea197f3c643")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("f0e2b21a-1431-4464-94cd-bea197f3c643")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("0b8da5f6-5ff0-4615-8e55-7a124c80c4c4")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("0b8da5f6-5ff0-4615-8e55-7a124c80c4c4")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("36cb546b-427a-4f4a-a0b6-2f56eb5e2d4d")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("36cb546b-427a-4f4a-a0b6-2f56eb5e2d4d")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("cbf9c831-8d0d-4016-b364-837e17d8e71d")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("cbf9c831-8d0d-4016-b364-837e17d8e71d")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item.
            /// </summary>
            [RepositoryItem("a1c43a20-073f-44cd-870a-3628914f712e")]
            public virtual Ranorex.TabPage ImageBasedAutomation
            {
                get
                {
                    return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item info.
            /// </summary>
            [RepositoryItemInfo("a1c43a20-073f-44cd-870a-3628914f712e")]
            public virtual RepoItemInfo ImageBasedAutomationInfo
            {
                get
                {
                    return _imagebasedautomationInfo;
                }
            }

            /// <summary>
            /// The ChkShowImage item.
            /// </summary>
            [RepositoryItem("c73b7c3e-c39f-48d8-b1a3-ee18cc7feb17")]
            public virtual Ranorex.CheckBox ChkShowImage
            {
                get
                {
                    return _chkshowimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowImage item info.
            /// </summary>
            [RepositoryItemInfo("c73b7c3e-c39f-48d8-b1a3-ee18cc7feb17")]
            public virtual RepoItemInfo ChkShowImageInfo
            {
                get
                {
                    return _chkshowimageInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("f5cb2886-f452-4640-a3a8-2d3c14f80937")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("f5cb2886-f452-4640-a3a8-2d3c14f80937")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }

            /// <summary>
            /// The RxTabcontrol folder.
            /// </summary>
            [RepositoryFolder("f28bdf02-fc2c-4ca3-9bc4-5bcd7446288e")]
            public virtual EpirocRepositoryFolders.RxTabcontrolFolder RxTabcontrol
            {
                get { return _rxtabcontrol; }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("3d8be692-86c1-441e-a334-c1c846b0ae56")]
            public virtual EpirocRepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }
        }

        /// <summary>
        /// The RxTabcontrolFolder folder.
        /// </summary>
        [RepositoryFolder("f28bdf02-fc2c-4ca3-9bc4-5bcd7446288e")]
        public partial class RxTabcontrolFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabcontrol  folder.
            /// </summary>
            public RxTabcontrolFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabcontrol", "", parentFolder, 30000, null, false, "f28bdf02-fc2c-4ca3-9bc4-5bcd7446288e", "")
            {
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "tabpagelist[@controlname='RxTabcontrol']/tabpage[@controlname='RxTabIntroduction']/text[@controlname='lblWelcomeMessage']", "", 30000, null, "52993c21-2794-4c1e-aa31-2b63988f9ef7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f28bdf02-fc2c-4ca3-9bc4-5bcd7446288e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f28bdf02-fc2c-4ca3-9bc4-5bcd7446288e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("52993c21-2794-4c1e-aa31-2b63988f9ef7")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("52993c21-2794-4c1e-aa31-2b63988f9ef7")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("3d8be692-86c1-441e-a334-c1c846b0ae56")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 0, null, false, "3d8be692-86c1-441e-a334-c1c846b0ae56", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/tabpage[@controlname='RxTabStandard']/?/?/text[@accessiblename='First name']", "", 30000, null, "478b16ed-8b38-4578-acd0-74d0ffabf258");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/tabpage[@controlname='RxTabStandard']/?/?/text[@accessiblename='Last name']", "", 30000, null, "ee3a3c91-c87e-4306-9860-217e5dfd0845");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3d8be692-86c1-441e-a334-c1c846b0ae56")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("478b16ed-8b38-4578-acd0-74d0ffabf258")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("478b16ed-8b38-4578-acd0-74d0ffabf258")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("ee3a3c91-c87e-4306-9860-217e5dfd0845")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("ee3a3c91-c87e-4306-9860-217e5dfd0845")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }
        }

        /// <summary>
        /// The TabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("2361754b-4a5c-4260-89b4-89f5afb417f9")]
        public partial class TabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ageInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbmaleInfo;

            /// <summary>
            /// Creates a new TabStandard  folder.
            /// </summary>
            public TabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("TabStandard", "/form[@controlname='RxMainFrame']/?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "2361754b-4a5c-4260-89b4-89f5afb417f9", "")
            {
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "acb67d18-9909-4b86-a2ce-0758a476cabc");
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", "", 30000, null, "b31a43c5-407d-4279-967a-abc977685f02");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@text=$Gender]", "", 30000, null, "dfd46ab0-5da1-4857-acba-fe6118c609e3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2361754b-4a5c-4260-89b4-89f5afb417f9")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2361754b-4a5c-4260-89b4-89f5afb417f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("acb67d18-9909-4b86-a2ce-0758a476cabc")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("acb67d18-9909-4b86-a2ce-0758a476cabc")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("b31a43c5-407d-4279-967a-abc977685f02")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("b31a43c5-407d-4279-967a-abc977685f02")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("dfd46ab0-5da1-4857-acba-fe6118c609e3")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("dfd46ab0-5da1-4857-acba-fe6118c609e3")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("a21e7b00-0963-46b3-b1ae-677b87a0ab01")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testingInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "a21e7b00-0963-46b3-b1ae-677b87a0ab01", "")
            {
                _testingInfo = new RepoItemInfo(this, "Testing", "listitem[@text=$Category]", "", 30000, null, "9521469f-947e-4958-bcf1-7f19dc5e3749");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a21e7b00-0963-46b3-b1ae-677b87a0ab01")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a21e7b00-0963-46b3-b1ae-677b87a0ab01")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("9521469f-947e-4958-bcf1-7f19dc5e3749")]
            public virtual Ranorex.ListItem Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("9521469f-947e-4958-bcf1-7f19dc5e3749")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("55446e64-e028-4fb0-a16c-52710daf9385")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            EpirocRepositoryFolders.CategoryFolder _category;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _gender1Info;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _clearInfo;
            RepoItemInfo _httpswwwranorexcomdatadriventestInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "55446e64-e028-4fb0-a16c-52710daf9385", "")
            {
                _category = new EpirocRepositoryFolders.CategoryFolder(this);
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", "", 30000, null, "5b75782b-105d-479f-ae42-1b678f149771");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", "", 30000, null, "dd11bec6-d2ff-49a3-b6d3-44e89267a898");
                _gender1Info = new RepoItemInfo(this, "Gender1", ".//td[#'gender']/table//input[@name='Gender' and @type='radio' and @value='male']", "", 30000, null, "c7dda421-cc8a-4f41-a7be-6305d491b052");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", "", 30000, null, "f992462c-e591-46b8-a2f3-bf04eea792ce");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", "", 30000, null, "251f71d8-0cba-4d9c-ab43-dc700e870678");
                _httpswwwranorexcomdatadriventestInfo = new RepoItemInfo(this, "HttpsWwwRanorexComDataDrivenTest", ".//div[#'productMenu']/div/div[2]/div[2]/div/div/ul/li[3]/a[@href>'https://www.ranorex.com/d']", "", 30000, null, "35f9598b-3238-4f14-a712-8c4439eb145c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55446e64-e028-4fb0-a16c-52710daf9385")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55446e64-e028-4fb0-a16c-52710daf9385")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("5b75782b-105d-479f-ae42-1b678f149771")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("5b75782b-105d-479f-ae42-1b678f149771")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("dd11bec6-d2ff-49a3-b6d3-44e89267a898")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("dd11bec6-d2ff-49a3-b6d3-44e89267a898")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Gender1 item.
            /// </summary>
            [RepositoryItem("c7dda421-cc8a-4f41-a7be-6305d491b052")]
            public virtual Ranorex.InputTag Gender1
            {
                get
                {
                    return _gender1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender1 item info.
            /// </summary>
            [RepositoryItemInfo("c7dda421-cc8a-4f41-a7be-6305d491b052")]
            public virtual RepoItemInfo Gender1Info
            {
                get
                {
                    return _gender1Info;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("f992462c-e591-46b8-a2f3-bf04eea792ce")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("f992462c-e591-46b8-a2f3-bf04eea792ce")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("251f71d8-0cba-4d9c-ab43-dc700e870678")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("251f71d8-0cba-4d9c-ab43-dc700e870678")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwRanorexComDataDrivenTest item.
            /// </summary>
            [RepositoryItem("35f9598b-3238-4f14-a712-8c4439eb145c")]
            public virtual Ranorex.ATag HttpsWwwRanorexComDataDrivenTest
            {
                get
                {
                    return _httpswwwranorexcomdatadriventestInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwRanorexComDataDrivenTest item info.
            /// </summary>
            [RepositoryItemInfo("35f9598b-3238-4f14-a712-8c4439eb145c")]
            public virtual RepoItemInfo HttpsWwwRanorexComDataDrivenTestInfo
            {
                get
                {
                    return _httpswwwranorexcomdatadriventestInfo;
                }
            }

            /// <summary>
            /// The Category folder.
            /// </summary>
            [RepositoryFolder("b483900b-f1b9-42de-a70b-9ded810ba4f8")]
            public virtual EpirocRepositoryFolders.CategoryFolder Category
            {
                get { return _category; }
            }
        }

        /// <summary>
        /// The CategoryFolder folder.
        /// </summary>
        [RepositoryFolder("b483900b-f1b9-42de-a70b-9ded810ba4f8")]
        public partial class CategoryFolder : RepoGenBaseFolder
        {
            RepoItemInfo _musicInfo;

            /// <summary>
            /// Creates a new Category  folder.
            /// </summary>
            public CategoryFolder(RepoGenBaseFolder parentFolder) :
                    base("Category", ".//select[#'Category']", parentFolder, 30000, null, false, "b483900b-f1b9-42de-a70b-9ded810ba4f8", "")
            {
                _musicInfo = new RepoItemInfo(this, "Music", "option[@value='Music']", "", 30000, null, "cb62792e-c2ed-446d-a610-2f4d92d2e22b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b483900b-f1b9-42de-a70b-9ded810ba4f8")]
            public virtual Ranorex.SelectTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b483900b-f1b9-42de-a70b-9ded810ba4f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("cb62792e-c2ed-446d-a610-2f4d92d2e22b")]
            public virtual Ranorex.OptionTag Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("cb62792e-c2ed-446d-a610-2f4d92d2e22b")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }
        }

        /// <summary>
        /// The HowToCreateAUserRatingScorecardAppFolder folder.
        /// </summary>
        [RepositoryFolder("7011a435-979b-4fe1-8005-f106276d604b")]
        public partial class HowToCreateAUserRatingScorecardAppFolder : RepoGenBaseFolder
        {
            EpirocRepositoryFolders.MainFolder _main;
            RepoItemInfo _overlayInfo;

            /// <summary>
            /// Creates a new HowToCreateAUserRatingScorecard  folder.
            /// </summary>
            public HowToCreateAUserRatingScorecardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HowToCreateAUserRatingScorecard", "/dom[@domain='www.w3schools.com']", parentFolder, 30000, null, false, "7011a435-979b-4fe1-8005-f106276d604b", "")
            {
                _main = new EpirocRepositoryFolders.MainFolder(this);
                _overlayInfo = new RepoItemInfo(this, "Overlay", ".//div[#'overlay']", "", 30000, null, "e5720300-89c2-4daf-b8a0-17ea1e5b75d4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7011a435-979b-4fe1-8005-f106276d604b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7011a435-979b-4fe1-8005-f106276d604b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Overlay item.
            /// </summary>
            [RepositoryItem("e5720300-89c2-4daf-b8a0-17ea1e5b75d4")]
            public virtual Ranorex.DivTag Overlay
            {
                get
                {
                    return _overlayInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Overlay item info.
            /// </summary>
            [RepositoryItemInfo("e5720300-89c2-4daf-b8a0-17ea1e5b75d4")]
            public virtual RepoItemInfo OverlayInfo
            {
                get
                {
                    return _overlayInfo;
                }
            }

            /// <summary>
            /// The Main folder.
            /// </summary>
            [RepositoryFolder("46e73746-36ff-4167-aaa0-460d4f9bfcee")]
            public virtual EpirocRepositoryFolders.MainFolder Main
            {
                get { return _main; }
            }
        }

        /// <summary>
        /// The MainFolder folder.
        /// </summary>
        [RepositoryFolder("46e73746-36ff-4167-aaa0-460d4f9bfcee")]
        public partial class MainFolder : RepoGenBaseFolder
        {
            RepoItemInfo _w3buttonw3greenInfo;
            RepoItemInfo _nextbtnInfo;
            RepoItemInfo _someh1tagInfo;
            RepoItemInfo _previousbtnInfo;

            /// <summary>
            /// Creates a new Main  folder.
            /// </summary>
            public MainFolder(RepoGenBaseFolder parentFolder) :
                    base("Main", ".//div[#'main']", parentFolder, 30000, null, false, "46e73746-36ff-4167-aaa0-460d4f9bfcee", "")
            {
                _w3buttonw3greenInfo = new RepoItemInfo(this, "W3ButtonW3Green", "button", "", 30000, null, "93d800cf-adde-4cbe-b2e8-514cde8d97e9");
                _nextbtnInfo = new RepoItemInfo(this, "NextBtn", "div[2]/a[2]", "", 30000, null, "78f2482e-c3ea-4acc-a7d0-2268f4c7ab85");
                _someh1tagInfo = new RepoItemInfo(this, "SomeH1Tag", "h1", "", 30000, null, "555f8a3b-2329-47ea-a451-cb26550be6e6");
                _previousbtnInfo = new RepoItemInfo(this, "PreviousBtn", "div[2]/a[1]", "", 30000, null, "95604e52-f961-4b87-8fad-bbc0a162e241");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("46e73746-36ff-4167-aaa0-460d4f9bfcee")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("46e73746-36ff-4167-aaa0-460d4f9bfcee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The W3ButtonW3Green item.
            /// </summary>
            [RepositoryItem("93d800cf-adde-4cbe-b2e8-514cde8d97e9")]
            public virtual Ranorex.ButtonTag W3ButtonW3Green
            {
                get
                {
                    return _w3buttonw3greenInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The W3ButtonW3Green item info.
            /// </summary>
            [RepositoryItemInfo("93d800cf-adde-4cbe-b2e8-514cde8d97e9")]
            public virtual RepoItemInfo W3ButtonW3GreenInfo
            {
                get
                {
                    return _w3buttonw3greenInfo;
                }
            }

            /// <summary>
            /// The NextBtn item.
            /// </summary>
            [RepositoryItem("78f2482e-c3ea-4acc-a7d0-2268f4c7ab85")]
            public virtual Ranorex.ATag NextBtn
            {
                get
                {
                    return _nextbtnInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NextBtn item info.
            /// </summary>
            [RepositoryItemInfo("78f2482e-c3ea-4acc-a7d0-2268f4c7ab85")]
            public virtual RepoItemInfo NextBtnInfo
            {
                get
                {
                    return _nextbtnInfo;
                }
            }

            /// <summary>
            /// The SomeH1Tag item.
            /// </summary>
            [RepositoryItem("555f8a3b-2329-47ea-a451-cb26550be6e6")]
            public virtual Ranorex.H1Tag SomeH1Tag
            {
                get
                {
                    return _someh1tagInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The SomeH1Tag item info.
            /// </summary>
            [RepositoryItemInfo("555f8a3b-2329-47ea-a451-cb26550be6e6")]
            public virtual RepoItemInfo SomeH1TagInfo
            {
                get
                {
                    return _someh1tagInfo;
                }
            }

            /// <summary>
            /// The PreviousBtn item.
            /// </summary>
            [RepositoryItem("95604e52-f961-4b87-8fad-bbc0a162e241")]
            public virtual Ranorex.ATag PreviousBtn
            {
                get
                {
                    return _previousbtnInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PreviousBtn item info.
            /// </summary>
            [RepositoryItemInfo("95604e52-f961-4b87-8fad-bbc0a162e241")]
            public virtual RepoItemInfo PreviousBtnInfo
            {
                get
                {
                    return _previousbtnInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("dfecbb30-89a0-451e-beac-7b638b8a0c99")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rxtestapp10Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "dfecbb30-89a0-451e-beac-7b638b8a0c99", "")
            {
                _rxtestapp10Info = new RepoItemInfo(this, "RXTestApp10", ".//toolbar[@accessiblename='Running applications']/button[@accessiblename='RX_Test_App_10']", "", 30000, null, "617e010a-56eb-4678-b177-45d0a1014e73");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dfecbb30-89a0-451e-beac-7b638b8a0c99")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dfecbb30-89a0-451e-beac-7b638b8a0c99")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RXTestApp10 item.
            /// </summary>
            [RepositoryItem("617e010a-56eb-4678-b177-45d0a1014e73")]
            public virtual Ranorex.Button RXTestApp10
            {
                get
                {
                    return _rxtestapp10Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RXTestApp10 item info.
            /// </summary>
            [RepositoryItemInfo("617e010a-56eb-4678-b177-45d0a1014e73")]
            public virtual RepoItemInfo RXTestApp10Info
            {
                get
                {
                    return _rxtestapp10Info;
                }
            }
        }

        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("6ff410e8-7fb8-49be-b9d0-38ee8c7def27")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _progressbar1Info;
            RepoItemInfo _btresetuiInfo;
            RepoItemInfo _btcloseInfo;
            RepoItemInfo _lbprogressInfo;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 30000, null, true, "6ff410e8-7fb8-49be-b9d0-38ee8c7def27", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlname='button1']", "", 30000, null, "05f0ab8b-3a7c-4b88-a5e4-dfb7edbc9457");
                _progressbar1Info = new RepoItemInfo(this, "ProgressBar1", "progressbar[@controlname='progressBar1']", "", 30000, null, "6d0e12c5-0994-4270-95e5-8137f86118b6");
                _btresetuiInfo = new RepoItemInfo(this, "BtResetUI", "button[@controlname='btResetUI']", "", 30000, null, "c1a3fd53-0aa2-4290-bf65-99393dd9288b");
                _btcloseInfo = new RepoItemInfo(this, "BtClose", "button[@controlname='btClose']", "", 30000, null, "8d7b8755-b8a8-446d-86b6-13e27ae28cbc");
                _lbprogressInfo = new RepoItemInfo(this, "LbProgress", "text[@controlname='lbProgress']", "", 30000, null, "2f334339-40f6-49d7-ab67-ca8765d2a7b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ff410e8-7fb8-49be-b9d0-38ee8c7def27")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ff410e8-7fb8-49be-b9d0-38ee8c7def27")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("05f0ab8b-3a7c-4b88-a5e4-dfb7edbc9457")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("05f0ab8b-3a7c-4b88-a5e4-dfb7edbc9457")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The ProgressBar1 item.
            /// </summary>
            [RepositoryItem("6d0e12c5-0994-4270-95e5-8137f86118b6")]
            public virtual Ranorex.ProgressBar ProgressBar1
            {
                get
                {
                    return _progressbar1Info.CreateAdapter<Ranorex.ProgressBar>(true);
                }
            }

            /// <summary>
            /// The ProgressBar1 item info.
            /// </summary>
            [RepositoryItemInfo("6d0e12c5-0994-4270-95e5-8137f86118b6")]
            public virtual RepoItemInfo ProgressBar1Info
            {
                get
                {
                    return _progressbar1Info;
                }
            }

            /// <summary>
            /// The BtResetUI item.
            /// </summary>
            [RepositoryItem("c1a3fd53-0aa2-4290-bf65-99393dd9288b")]
            public virtual Ranorex.Button BtResetUI
            {
                get
                {
                    return _btresetuiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtResetUI item info.
            /// </summary>
            [RepositoryItemInfo("c1a3fd53-0aa2-4290-bf65-99393dd9288b")]
            public virtual RepoItemInfo BtResetUIInfo
            {
                get
                {
                    return _btresetuiInfo;
                }
            }

            /// <summary>
            /// The BtClose item.
            /// </summary>
            [RepositoryItem("8d7b8755-b8a8-446d-86b6-13e27ae28cbc")]
            public virtual Ranorex.Button BtClose
            {
                get
                {
                    return _btcloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtClose item info.
            /// </summary>
            [RepositoryItemInfo("8d7b8755-b8a8-446d-86b6-13e27ae28cbc")]
            public virtual RepoItemInfo BtCloseInfo
            {
                get
                {
                    return _btcloseInfo;
                }
            }

            /// <summary>
            /// The LbProgress item.
            /// </summary>
            [RepositoryItem("2f334339-40f6-49d7-ab67-ca8765d2a7b6")]
            public virtual Ranorex.Text LbProgress
            {
                get
                {
                    return _lbprogressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LbProgress item info.
            /// </summary>
            [RepositoryItemInfo("2f334339-40f6-49d7-ab67-ca8765d2a7b6")]
            public virtual RepoItemInfo LbProgressInfo
            {
                get
                {
                    return _lbprogressInfo;
                }
            }
        }

        /// <summary>
        /// The Paint3DAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ee59637-ee41-4f3e-b335-d7c60cd2ef04")]
        public partial class Paint3DAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tooltextInfo;
            ZoomInteractorInfoClass _zoominteractorInfo;
            RepoItemInfo _switchviewtextInfo;

            /// <summary>
            /// Creates a new Paint3D  folder.
            /// </summary>
            public Paint3DAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Paint3D", "/winapp[@packagename='Microsoft.MSPaint']", parentFolder, 30000, null, true, "7ee59637-ee41-4f3e-b335-d7c60cd2ef04", "")
            {
                _tooltextInfo = new RepoItemInfo(this, "ToolText", ".//listitem[@automationid='SelectionTool']/text[@automationid='ToolText']", "", 30000, null, "53a69e5a-c49b-4ef3-8eef-38de4ee8d461");
                _zoominteractorInfo = new ZoomInteractorInfoClass(this);
                _switchviewtextInfo = new RepoItemInfo(this, "SwitchViewText", ".//text[@automationid='SwitchViewText']", "", 30000, null, "9657d0cb-6ae7-4add-981f-dd412da05bf5");
            }

            /// <summary>
            /// The ZoomInteractorInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("eb38c787-a9cb-4cad-a76d-69c9304f7be4")]
            public class ZoomInteractorInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ZoomInteractorInfoClass class constructor.
                /// </summary>
                public ZoomInteractorInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ZoomInteractor", "?/?/element[@automationid='ZoomInteractor']", 30000, null, "eb38c787-a9cb-4cad-a76d-69c9304f7be4")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("db646a31-8280-4b4d-9b6c-6ddfa964d96a")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("db646a31-8280-4b4d-9b6c-6ddfa964d96a");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("db646a31-8280-4b4d-9b6c-6ddfa964d96a")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("db646a31-8280-4b4d-9b6c-6ddfa964d96a", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("b49c71f2-3b4f-4c3b-84cf-cece58a0f0ed")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("b49c71f2-3b4f-4c3b-84cf-cece58a0f0ed");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b49c71f2-3b4f-4c3b-84cf-cece58a0f0ed")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b49c71f2-3b4f-4c3b-84cf-cece58a0f0ed", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ee59637-ee41-4f3e-b335-d7c60cd2ef04")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ee59637-ee41-4f3e-b335-d7c60cd2ef04")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ToolText item.
            /// </summary>
            [RepositoryItem("53a69e5a-c49b-4ef3-8eef-38de4ee8d461")]
            public virtual Ranorex.Text ToolText
            {
                get
                {
                    return _tooltextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ToolText item info.
            /// </summary>
            [RepositoryItemInfo("53a69e5a-c49b-4ef3-8eef-38de4ee8d461")]
            public virtual RepoItemInfo ToolTextInfo
            {
                get
                {
                    return _tooltextInfo;
                }
            }

            /// <summary>
            /// The ZoomInteractor item.
            /// </summary>
            [RepositoryItem("eb38c787-a9cb-4cad-a76d-69c9304f7be4")]
            public virtual Ranorex.Unknown ZoomInteractor
            {
                get
                {
                    return _zoominteractorInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ZoomInteractor item info.
            /// </summary>
            [RepositoryItemInfo("eb38c787-a9cb-4cad-a76d-69c9304f7be4")]
            public virtual ZoomInteractorInfoClass ZoomInteractorInfo
            {
                get
                {
                    return _zoominteractorInfo;
                }
            }

            /// <summary>
            /// The SwitchViewText item.
            /// </summary>
            [RepositoryItem("9657d0cb-6ae7-4add-981f-dd412da05bf5")]
            public virtual Ranorex.Text SwitchViewText
            {
                get
                {
                    return _switchviewtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SwitchViewText item info.
            /// </summary>
            [RepositoryItemInfo("9657d0cb-6ae7-4add-981f-dd412da05bf5")]
            public virtual RepoItemInfo SwitchViewTextInfo
            {
                get
                {
                    return _switchviewtextInfo;
                }
            }
        }

        /// <summary>
        /// The RanorexAppFolder folder.
        /// </summary>
        [RepositoryFolder("b935fa11-e3eb-4eee-becf-c5799edd1fbe")]
        public partial class RanorexAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorexInfo;
            RepoItemInfo _programfilesx86Info;
            RepoItemInfo _windowscInfo;
            RepoItemInfo _downInfo;

            /// <summary>
            /// Creates a new Ranorex  folder.
            /// </summary>
            public RanorexAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Ranorex", "/form[@title='Ranorex']", parentFolder, 30000, null, true, "b935fa11-e3eb-4eee-becf-c5799edd1fbe", "")
            {
                _ranorexInfo = new RepoItemInfo(this, "Ranorex", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[4]/?/?/tree[@controlid='100']//treeitem[@text='Program Files (x86)']/treeitem[@text='Ranorex']", "", 30000, null, "4957178d-71a8-4bcd-b3dc-1ced9a750d06");
                _programfilesx86Info = new RepoItemInfo(this, "ProgramFilesX86", "element[@class='ShellTabWindowClass']/element[@class='DUIViewWndClassName']/container/element[4]/?/?/tree[@controlid='100']//treeitem[@text='Program Files (x86)']", "", 30000, null, "54e7d503-1ee0-4b90-9a9c-cce6f76b9f70");
                _windowscInfo = new RepoItemInfo(this, "WindowsC", "element[@class='ShellTabWindowClass']/?/?/container[@class='DirectUIHWND']/element[4]/?/?/tree[@controlid='100']//treeitem[@text='Windows (C:)']", "", 30000, null, "c1dbc0e4-394e-46ff-992d-a24c32b422d4");
                _downInfo = new RepoItemInfo(this, "Down", "element[@class='ShellTabWindowClass']//tree[@controlid='100']/scrollbar[@style='Vertical']/button[@text='Down']", "", 30000, null, "29541cdb-b823-4937-af2a-68ef57d9f774");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b935fa11-e3eb-4eee-becf-c5799edd1fbe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b935fa11-e3eb-4eee-becf-c5799edd1fbe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Ranorex item.
            /// </summary>
            [RepositoryItem("4957178d-71a8-4bcd-b3dc-1ced9a750d06")]
            public virtual Ranorex.TreeItem Ranorex
            {
                get
                {
                    return _ranorexInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Ranorex item info.
            /// </summary>
            [RepositoryItemInfo("4957178d-71a8-4bcd-b3dc-1ced9a750d06")]
            public virtual RepoItemInfo RanorexInfo
            {
                get
                {
                    return _ranorexInfo;
                }
            }

            /// <summary>
            /// The ProgramFilesX86 item.
            /// </summary>
            [RepositoryItem("54e7d503-1ee0-4b90-9a9c-cce6f76b9f70")]
            public virtual Ranorex.TreeItem ProgramFilesX86
            {
                get
                {
                    return _programfilesx86Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ProgramFilesX86 item info.
            /// </summary>
            [RepositoryItemInfo("54e7d503-1ee0-4b90-9a9c-cce6f76b9f70")]
            public virtual RepoItemInfo ProgramFilesX86Info
            {
                get
                {
                    return _programfilesx86Info;
                }
            }

            /// <summary>
            /// The WindowsC item.
            /// </summary>
            [RepositoryItem("c1dbc0e4-394e-46ff-992d-a24c32b422d4")]
            public virtual Ranorex.TreeItem WindowsC
            {
                get
                {
                    return _windowscInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The WindowsC item info.
            /// </summary>
            [RepositoryItemInfo("c1dbc0e4-394e-46ff-992d-a24c32b422d4")]
            public virtual RepoItemInfo WindowsCInfo
            {
                get
                {
                    return _windowscInfo;
                }
            }

            /// <summary>
            /// The Down item.
            /// </summary>
            [RepositoryItem("29541cdb-b823-4937-af2a-68ef57d9f774")]
            public virtual Ranorex.Button Down
            {
                get
                {
                    return _downInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Down item info.
            /// </summary>
            [RepositoryItemInfo("29541cdb-b823-4937-af2a-68ef57d9f774")]
            public virtual RepoItemInfo DownInfo
            {
                get
                {
                    return _downInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
