///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Epiroc
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FileUpload recording.
    /// </summary>
    [TestModule("35e6941f-20f7-4f7b-9633-85e5c83dadca", ModuleType.Recording, 1)]
    public partial class FileUpload : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EpirocRepository repository.
        /// </summary>
        public static EpirocRepository repo = EpirocRepository.Instance;

        static FileUpload instance = new FileUpload();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FileUpload()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FileUpload Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.Button1' at 70;16.", repo.Form1.Button1Info, new RecordItemIndex(0));
            repo.Form1.Button1.Click("70;16");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(1));
            //Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m for the attribute 'Text' to contain the specified value '100'. Associated repository item: 'Form1.LbProgress'", repo.Form1.LbProgressInfo, new RecordItemIndex(2));
            repo.Form1.LbProgressInfo.WaitForAttributeContains(60000, "Text", "100");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.BtResetUI' at 36;11.", repo.Form1.BtResetUIInfo, new RecordItemIndex(3));
            repo.Form1.BtResetUI.Click("36;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.BtClose' at 75;8.", repo.Form1.BtCloseInfo, new RecordItemIndex(4));
            repo.Form1.BtClose.Click("75;8");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Form1.Self, false, new RecordItemIndex(5));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
