///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Epiroc
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FindPath recording.
    /// </summary>
    [TestModule("a8edc79c-d56d-4403-b93b-c15df465d303", ModuleType.Recording, 1)]
    public partial class FindPath : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EpirocRepository repository.
        /// </summary>
        public static EpirocRepository repo = EpirocRepository.Instance;

        static FindPath instance = new FindPath();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FindPath()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FindPath Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            PathFinder(repo.Ranorex.Down, repo.Ranorex.WindowsC);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ranorex.WindowsC' at Center.", repo.Ranorex.WindowsCInfo, new RecordItemIndex(1));
            repo.Ranorex.WindowsC.DoubleClick();
            Delay.Milliseconds(0);
            
            PathFinder(repo.Ranorex.Down, repo.Ranorex.ProgramFilesX86);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ranorex.ProgramFilesX86' at Center.", repo.Ranorex.ProgramFilesX86Info, new RecordItemIndex(3));
            repo.Ranorex.ProgramFilesX86.DoubleClick();
            Delay.Milliseconds(0);
            
            PathFinder(repo.Ranorex.Down, repo.Ranorex.Ranorex);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Ranorex.Ranorex' at Center.", repo.Ranorex.RanorexInfo, new RecordItemIndex(5));
            repo.Ranorex.Ranorex.DoubleClick();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
