///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Epiroc
{
    public partial class FindPath
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void PathFinder(Adapter DownBtn, Adapter PN)
        {
            int i=0;
            
            while(i<50)
            {
            	i++;
            	
            	DownBtn.Click();
            	
            	if(PN.Visible)
            	{
            		i=100;
            		DownBtn.Click();
            		Report.Info("Item found");
            	}
            }
        }

    }
}
