///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Epiroc
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FullTest recording.
    /// </summary>
    [TestModule("46514c1a-2b62-4286-a761-7ce0bda112e4", ModuleType.Recording, 1)]
    public partial class FullTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EpirocRepository repository.
        /// </summary>
        public static EpirocRepository repo = EpirocRepository.Instance;

        static FullTest instance = new FullTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FullTest()
        {
            Category = "Testing";
            GetWelcomeMessage = "-1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FullTest Instance
        {
            get { return instance; }
        }

#region Variables

        string _GetWelcomeMessage;

        /// <summary>
        /// Gets or sets the value of variable GetWelcomeMessage.
        /// </summary>
        [TestVariable("2541c530-19ef-46ef-b468-8d2b90b9aabd")]
        public string GetWelcomeMessage
        {
            get { return _GetWelcomeMessage; }
            set { _GetWelcomeMessage = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Category.
        /// </summary>
        [TestVariable("808814a3-e7ec-4eb8-8bfd-834506eda953")]
        public string Category
        {
            get { return repo.Category; }
            set { repo.Category = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("b48bc0de-3127-4c6e-8677-6fe4241727e9")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Start AUT
            Report.Log(ReportLevel.Info, "Section", "Start AUT", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\mkadiwala\\Desktop\\RCT\\RxDemoApp.exe' in normal mode.", new RecordItemIndex(1));
            Host.Local.RunApplication("C:\\Users\\mkadiwala\\Desktop\\RCT\\RxDemoApp.exe", "", "C:\\Users\\mkadiwala\\Desktop\\RCT", false);
            Delay.Milliseconds(0);
            
            // Tab - Introduction
            Report.Log(ReportLevel.Info, "Section", "Tab - Introduction", new RecordItemIndex(2));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.Introduction' at Center.", repo.DemoApp.IntroductionInfo, new RecordItemIndex(3));
            //repo.DemoApp.Introduction.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'DemoApp.Introduction'.", repo.DemoApp.IntroductionInfo, new RecordItemIndex(4));
            repo.DemoApp.Introduction.Select();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.EnterYourName' at 34;7.", repo.DemoApp.EnterYourNameInfo, new RecordItemIndex(5));
            //repo.DemoApp.EnterYourName.Click("34;7");
            //Delay.Milliseconds(0);
            
            // Enter Name
            //Report.Log(ReportLevel.Info, "Keyboard", "Enter Name\r\nKey sequence '●●●●●●' with focus on 'DemoApp.EnterYourName'.", repo.DemoApp.EnterYourNameInfo, new RecordItemIndex(6));
            //repo.DemoApp.EnterYourName.PressKeys("Mickey");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Mouse' on item 'DemoApp.EnterYourName'.", repo.DemoApp.EnterYourNameInfo, new RecordItemIndex(7));
            repo.DemoApp.EnterYourName.Element.SetAttributeValue("Text", "Mouse");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.BtnSubmitUserName' at Center.", repo.DemoApp.BtnSubmitUserNameInfo, new RecordItemIndex(8));
            //repo.DemoApp.BtnSubmitUserName.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'DemoApp.BtnSubmitUserName'.", repo.DemoApp.BtnSubmitUserNameInfo, new RecordItemIndex(9));
            repo.DemoApp.BtnSubmitUserName.Press();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeRegex (Text~'Welcome') on item 'DemoApp.RxTabcontrol.LblWelcomeMessage'.", repo.DemoApp.RxTabcontrol.LblWelcomeMessageInfo, new RecordItemIndex(10));
                Validate.AttributeRegex(repo.DemoApp.RxTabcontrol.LblWelcomeMessageInfo, "Text", new Regex("Welcome"), null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.DemoApp.RxTabcontrol.LblWelcomeMessage, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'DemoApp.RxTabcontrol.LblWelcomeMessage' and assigning its value to variable 'GetWelcomeMessage'.", repo.DemoApp.RxTabcontrol.LblWelcomeMessageInfo, new RecordItemIndex(12));
            GetWelcomeMessage = repo.DemoApp.RxTabcontrol.LblWelcomeMessage.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            // Tab - Database
            Report.Log(ReportLevel.Info, "Section", "Tab - Database", new RecordItemIndex(13));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.TestDatabase' at 47;8.", repo.DemoApp.TestDatabaseInfo, new RecordItemIndex(14));
            //repo.DemoApp.TestDatabase.Click("47;8");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'DemoApp.TestDatabase'.", repo.DemoApp.TestDatabaseInfo, new RecordItemIndex(15));
            repo.DemoApp.TestDatabase.Select();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.Login.FirstName' at 65;13.", repo.DemoApp.Login.FirstNameInfo, new RecordItemIndex(16));
            //repo.DemoApp.Login.FirstName.Click("65;13");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Mubin' with focus on 'DemoApp.Login.FirstName'.", repo.DemoApp.Login.FirstNameInfo, new RecordItemIndex(17));
            //repo.DemoApp.Login.FirstName.PressKeys("Mubin");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$GetWelcomeMessage' on item 'DemoApp.Login.FirstName'.", repo.DemoApp.Login.FirstNameInfo, new RecordItemIndex(18));
            repo.DemoApp.Login.FirstName.Element.SetAttributeValue("Text", GetWelcomeMessage);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.Login.LastName' at 26;15.", repo.DemoApp.Login.LastNameInfo, new RecordItemIndex(19));
            //repo.DemoApp.Login.LastName.Click("26;15");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Kadiwala' with focus on 'DemoApp.Login.LastName'.", repo.DemoApp.Login.LastNameInfo, new RecordItemIndex(20));
            //repo.DemoApp.Login.LastName.PressKeys("Kadiwala");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Duck' on item 'DemoApp.Login.LastName'.", repo.DemoApp.Login.LastNameInfo, new RecordItemIndex(21));
            repo.DemoApp.Login.LastName.Element.SetAttributeValue("Text", "Duck");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.DemoApp.Self, false, new RecordItemIndex(22));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TabStandard.Open' at 8;15.", repo.TabStandard.OpenInfo, new RecordItemIndex(23));
            //repo.TabStandard.Open.Click("8;15");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'TabStandard.Open'.", repo.TabStandard.OpenInfo, new RecordItemIndex(24));
            repo.TabStandard.Open.Press();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Testing' at 99;9.", repo.List1000.TestingInfo, new RecordItemIndex(25));
            //repo.List1000.Testing.Click("99;9");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'List1000.Testing'.", repo.List1000.TestingInfo, new RecordItemIndex(26));
            repo.List1000.Testing.Select();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'TabStandard.Age' at 36;6.", repo.TabStandard.AgeInfo, new RecordItemIndex(27));
            //repo.TabStandard.Age.DoubleClick("36;6");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'TabStandard.Age'.", repo.TabStandard.AgeInfo, new RecordItemIndex(28));
            //Keyboard.PrepareFocus(repo.TabStandard.Age);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '35' with focus on 'TabStandard.Age'.", repo.TabStandard.AgeInfo, new RecordItemIndex(29));
            //repo.TabStandard.Age.PressKeys("35");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '35' on item 'TabStandard.Age'.", repo.TabStandard.AgeInfo, new RecordItemIndex(30));
            repo.TabStandard.Age.Element.SetAttributeValue("Text", "35");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TabStandard.RdbMale' at 8;7.", repo.TabStandard.RdbMaleInfo, new RecordItemIndex(31));
            //repo.TabStandard.RdbMale.Click("8;7");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'TabStandard.RdbMale'.", repo.TabStandard.RdbMaleInfo, new RecordItemIndex(32));
            repo.TabStandard.RdbMale.Select();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.BtnAddPerson' at 44;6.", repo.DemoApp.BtnAddPersonInfo, new RecordItemIndex(33));
            //repo.DemoApp.BtnAddPerson.Click("44;6");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'DemoApp.BtnAddPerson'.", repo.DemoApp.BtnAddPersonInfo, new RecordItemIndex(34));
            repo.DemoApp.BtnAddPerson.Press();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='1') on item 'DemoApp.LblNumberOfPersonsNumber'.", repo.DemoApp.LblNumberOfPersonsNumberInfo, new RecordItemIndex(35));
                Validate.AttributeEqual(repo.DemoApp.LblNumberOfPersonsNumberInfo, "Text", "1", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(35)); }
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.DemoApp.LblNumberOfPersonsNumber, false, new RecordItemIndex(36));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.DemoApp.Self, false, new RecordItemIndex(37));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.BtnDeletePerson' at 38;8.", repo.DemoApp.BtnDeletePersonInfo, new RecordItemIndex(38));
            //repo.DemoApp.BtnDeletePerson.Click("38;8");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'DemoApp.BtnDeletePerson'.", repo.DemoApp.BtnDeletePersonInfo, new RecordItemIndex(39));
            repo.DemoApp.BtnDeletePerson.Press();
            Delay.Milliseconds(0);
            
            // Tab - Image
            Report.Log(ReportLevel.Info, "Section", "Tab - Image", new RecordItemIndex(40));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.ImageBasedAutomation' at 66;10.", repo.DemoApp.ImageBasedAutomationInfo, new RecordItemIndex(41));
            //repo.DemoApp.ImageBasedAutomation.Click("66;10");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'DemoApp.ImageBasedAutomation'.", repo.DemoApp.ImageBasedAutomationInfo, new RecordItemIndex(42));
            repo.DemoApp.ImageBasedAutomation.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Image Tab Teest", new RecordItemIndex(43));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(44));
            Delay.Duration(500, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.ChkShowImage' at 6;11.", repo.DemoApp.ChkShowImageInfo, new RecordItemIndex(45));
            //repo.DemoApp.ChkShowImage.Click("6;11");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Checked to 'true' on item 'DemoApp.ChkShowImage'.", repo.DemoApp.ChkShowImageInfo, new RecordItemIndex(46));
            repo.DemoApp.ChkShowImage.Element.SetAttributeValue("Checked", "true");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.DemoApp.ChkShowImage, false, new RecordItemIndex(47));
            
            // Close AUT
            Report.Log(ReportLevel.Info, "Section", "Close AUT", new RecordItemIndex(48));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DemoApp.RxButtonExit' at 31;9.", repo.DemoApp.RxButtonExitInfo, new RecordItemIndex(49));
            //repo.DemoApp.RxButtonExit.Click("31;9");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'DemoApp.RxButtonExit'.", repo.DemoApp.RxButtonExitInfo, new RecordItemIndex(50));
            repo.DemoApp.RxButtonExit.Press();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
