///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Epiroc
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SalesforceRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f5e4403b-9c19-4dc6-9763-bf4b02cf6f96")]
    public partial class SalesforceRepository : RepoGenBaseFolder
    {
        static SalesforceRepository instance = new SalesforceRepository();
        SalesforceRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the SalesforceRepository element repository.
        /// </summary>
        [RepositoryFolder("f5e4403b-9c19-4dc6-9763-bf4b02cf6f96")]
        public static SalesforceRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SalesforceRepository() 
            : base("SalesforceRepository", "/", null, 0, false, "f5e4403b-9c19-4dc6-9763-bf4b02cf6f96", ".\\RepositoryImages\\SalesforceRepositoryf5e4403b.rximgres")
        {
            _calculator = new SalesforceRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f5e4403b-9c19-4dc6-9763-bf4b02cf6f96")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("c9c2563f-d320-4292-afd5-61d17aaf827e")]
        public virtual SalesforceRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SalesforceRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("c9c2563f-d320-4292-afd5-61d17aaf827e")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num7buttonInfo;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _text9Info;
            RepoItemInfo _sometext1Info;
            RepoItemInfo _sometext2Info;
            RepoItemInfo _normaloutputInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "c9c2563f-d320-4292-afd5-61d17aaf827e", "")
            {
                _num7buttonInfo = new RepoItemInfo(this, "Num7Button", ".//button[@automationid='num7Button']", "", 30000, null, "9de793e8-8818-4bb4-9aba-fdae68cfac6b");
                _sometextInfo = new RepoItemInfo(this, "SomeText", ".//button[@automationid='plusButton']/text[@name='']", "", 30000, null, "17e2b2cd-6c41-46eb-9bdc-3c364864babe");
                _text9Info = new RepoItemInfo(this, "Text9", ".//button[@automationid='num9Button']/text[@name='9']", "", 30000, null, "08c9158f-66bc-4dfa-9daf-22d8b6815667");
                _sometext1Info = new RepoItemInfo(this, "SomeText1", ".//button[@automationid='multiplyButton']/text[@name='']", "", 30000, null, "7eb391a5-60fc-457e-b1d5-d7a0eab65724");
                _sometext2Info = new RepoItemInfo(this, "SomeText2", ".//button[@automationid='squareRootButton']/text[@name='']", "", 30000, null, "8d32675d-6699-4aba-88e5-8a86cab288ec");
                _normaloutputInfo = new RepoItemInfo(this, "NormalOutput", "?/?/text[@automationid='CalculatorResults']/?/?/text[@automationid='NormalOutput']", "", 1, null, "71fa8c7b-ef2a-4c5c-b700-ad24a96a73c2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c9c2563f-d320-4292-afd5-61d17aaf827e")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c9c2563f-d320-4292-afd5-61d17aaf827e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num7Button item.
            /// </summary>
            [RepositoryItem("9de793e8-8818-4bb4-9aba-fdae68cfac6b")]
            public virtual Ranorex.Button Num7Button
            {
                get
                {
                    return _num7buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num7Button item info.
            /// </summary>
            [RepositoryItemInfo("9de793e8-8818-4bb4-9aba-fdae68cfac6b")]
            public virtual RepoItemInfo Num7ButtonInfo
            {
                get
                {
                    return _num7buttonInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("17e2b2cd-6c41-46eb-9bdc-3c364864babe")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("17e2b2cd-6c41-46eb-9bdc-3c364864babe")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The Text9 item.
            /// </summary>
            [RepositoryItem("08c9158f-66bc-4dfa-9daf-22d8b6815667")]
            public virtual Ranorex.Text Text9
            {
                get
                {
                    return _text9Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text9 item info.
            /// </summary>
            [RepositoryItemInfo("08c9158f-66bc-4dfa-9daf-22d8b6815667")]
            public virtual RepoItemInfo Text9Info
            {
                get
                {
                    return _text9Info;
                }
            }

            /// <summary>
            /// The SomeText1 item.
            /// </summary>
            [RepositoryItem("7eb391a5-60fc-457e-b1d5-d7a0eab65724")]
            public virtual Ranorex.Text SomeText1
            {
                get
                {
                    return _sometext1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText1 item info.
            /// </summary>
            [RepositoryItemInfo("7eb391a5-60fc-457e-b1d5-d7a0eab65724")]
            public virtual RepoItemInfo SomeText1Info
            {
                get
                {
                    return _sometext1Info;
                }
            }

            /// <summary>
            /// The SomeText2 item.
            /// </summary>
            [RepositoryItem("8d32675d-6699-4aba-88e5-8a86cab288ec")]
            public virtual Ranorex.Text SomeText2
            {
                get
                {
                    return _sometext2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText2 item info.
            /// </summary>
            [RepositoryItemInfo("8d32675d-6699-4aba-88e5-8a86cab288ec")]
            public virtual RepoItemInfo SomeText2Info
            {
                get
                {
                    return _sometext2Info;
                }
            }

            /// <summary>
            /// The NormalOutput item.
            /// </summary>
            [RepositoryItem("71fa8c7b-ef2a-4c5c-b700-ad24a96a73c2")]
            public virtual Ranorex.Text NormalOutput
            {
                get
                {
                    return _normaloutputInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NormalOutput item info.
            /// </summary>
            [RepositoryItemInfo("71fa8c7b-ef2a-4c5c-b700-ad24a96a73c2")]
            public virtual RepoItemInfo NormalOutputInfo
            {
                get
                {
                    return _normaloutputInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
