///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Team5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Team5Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fb41ad3d-dd88-47bf-b5f0-d166271e285d")]
    public partial class Team5Repository : RepoGenBaseFolder
    {
        static Team5Repository instance = new Team5Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Team5Repository element repository.
        /// </summary>
        [RepositoryFolder("fb41ad3d-dd88-47bf-b5f0-d166271e285d")]
        public static Team5Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Team5Repository() 
            : base("Team5Repository", "/", null, 0, false, "fb41ad3d-dd88-47bf-b5f0-d166271e285d", ".\\RepositoryImages\\Team5Repositoryfb41ad3d.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fb41ad3d-dd88-47bf-b5f0-d166271e285d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Team5RepositoryFolders
    {
    }
#pragma warning restore 0436
}
